ai_world/models.py
from ai_world import db

class Question(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    subject = db.Column(db.String(200), nullable=False)
    content = db.Column(db.Text(), nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False)


class Answer(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    question_id = db.Column(db.Integer, db.ForeignKey('question.id', ondelete='CASCADE'))
    question = db.relationship('Question', backref=db.backref('answer_set'))
    content = db.Column(db.Text(), nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False)

ai_world/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from flask_dropzone import Dropzone

import config

db = SQLAlchemy()
migrate = Migrate()


def create_app():
    app = Flask(__name__)
    app.config.from_object(config)

    # ORM
    db.init_app(app)
    migrate.init_app(app, db)
    from . import models

    # 블루프린트
    from .views import main_views, face_analysis_views # , question_views, answer_views
    app.register_blueprint(main_views.bp)
    app.register_blueprint(face_analysis_views.bp)
    app.config.update(
        # Flask-Dropzone config:
        DROPZONE_ALLOWED_FILE_TYPE='image',
        DROPZONE_MAX_FILE_SIZE=3,
        DROPZONE_MAX_FILES=20,
        DROPZONE_UPLOAD_ON_CLICK=True
    )
    dropzone = Dropzone(app)
    # app.register_blueprint(answer_views.bp)

    return app

ai_world/views/face_analysis_views.py
import os
import json
import re

from PIL import Image
import flask
from flask import Blueprint, url_for, render_template, request
from flask import Blueprint, render_template
from werkzeug.utils import redirect
from torchvision import models
import torchvision.transforms as transforms
import hgtk


bp = Blueprint('face_analysis', __name__, url_prefix='/')
UPLOAD_PATH = 'ai_world/static/face_analysis/images/'
RELATIVE_PATH = 'face_analysis/images/'
ALLOWED_EXTENSIONS = set(['txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'])
imagenet_class_index = json.load(open('ai_world/static/imagenet_class_index.json'))
model = models.densenet121(pretrained=True)
model.eval()

def transform_image(image_path):
    my_transforms = transforms.Compose([transforms.Resize(255),
                                        transforms.CenterCrop(224),
                                        transforms.ToTensor(),
                                        transforms.Normalize(
                                            [0.485, 0.456, 0.406],
                                            [0.229, 0.224, 0.225])])
    image = Image.open(image_path)
    return my_transforms(image).unsqueeze(0)


def get_prediction(image_path):
    tensor = transform_image(image_path=image_path)
    outputs = model.forward(tensor)
    _, y_hat = outputs.max(1)
    predicted_idx = str(y_hat.item())
    return imagenet_class_index[predicted_idx]


def allowed_file(filename):
    return '.' in filename and \
        filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS


def isHangul(text):
    text = hgtk.text.decompose(text)
    hangul = re.compile('[ㄱ-ㅣ가-힣]+')
    hanCount = len(hangul.findall(text))
    return hanCount > 0


@bp.route('/')
def index():
    return redirect(url_for('face_analysis._result'))


@bp.route('/face_analysis/result', methods = ['GET','POST'])
def _result():
    if request.method == 'POST':
        f = request.files['file']        
        file_format = f.filename.split('.')[-1]
        upload_path = os.path.join(UPLOAD_PATH, f'image.{file_format}')
        relative_path = os.path.join(RELATIVE_PATH, f'image.{file_format}')
        f.save(upload_path)
        class_id, class_name = get_prediction(image_path = upload_path)
        output = {}
        output['image_path'] = relative_path
        output['class_name'] = class_name
        
    return render_template('face_analysis/result.html', output=output)

ai_world/views/main_views.py
from flask import Blueprint, url_for, render_template
from werkzeug.utils import redirect
import flask

bp = Blueprint('main', __name__, url_prefix='/')

@bp.route('/')
def index():
    return redirect(url_for('main._content_list'))

@bp.route('/content_list/')
def _content_list():
    content_list = ['Face analysis using AI', 'OCR for blackbox video']
    return render_template('main/content_list.html', content_list=content_list)

@bp.route('/content_list/<int:content_id>/')
def _content(content_id):
    return render_template(f'main/content_{content_id}.html')


# @bp.route('/')
# def index():
#     return redirect(url_for('question._list'))

ai_world/templates/face_analysis/result.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />

        <title>Face Analysis using AI</title>

        <link rel="icon" type="image/png" href="favicon.png" />
        <link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css" />

        <script defer src="https://pyscript.net/latest/pyscript.js"></script>
    </head>
    <py-script>
    </py-script>

    <body>
        {% if output.image_path %}
        당신이 제출한 사진은...<br> {{output.class_name}} ? <br>
        <img src={{url_for('static',filename=output.image_path)}} alt="이미지"
        width="10%" height="10%">
        {% else %}
        <tr>
        <td colspan="3">img가 없습니다.</td>
        </tr>
        {% endif %}

    </body>
</html>

ai_world/templates/main/content_0.html
<html lang="en">
    <!-- Design by foolishdeveloper.com -->
    
  <head> 
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>CSS Progress Bar</title>
    <link rel="stylesheet" href="../../static/face_analysis/style.css">
  </head>
  <body>
  <form action = "../../face_analysis/result" method = "POST" enctype = "multipart/form-data">
   <div class="center">
    <div class="form-input">
      <div class="preview">
        <img id="file-ip-1-preview">
      </div>
      <label for="file-ip-1">Upload Image</label>
      <input type="file" name="file" id="file-ip-1" accept="image/*" onchange="showPreview(event);">
    </div>
  </div> 
  </form>
  <script type="text/javascript">
    function showPreview(event){
    if(event.target.files.length > 0){
      var src = URL.createObjectURL(event.target.files[0]);
      var preview = document.getElementById("file-ip-1-preview");
      preview.src = src;
      preview.style.display = "block";
    }
  }
  </script>

  </body>
  </html>
  

ai_world/templates/main/content_1.html
<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>내용</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td> OCR for blackbox video </td>
        </tr>
        </tbody>
    </table>
</div>

ai_world/templates/main/content_list.html
<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>컨텐츠</th>
        </tr>
        </thead>
        <tbody>
        {% if content_list %}
        {% for content in content_list %}
        <tr>
            <td>{{ loop.index - 1}}</td>
            <td>
                <a href="{{ url_for('main._content', content_id=loop.index - 1) }}">{{ content }}</a>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>